# Generated by Django 2.2.12 on 2021-09-28 15:19

import contractor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0002_initial2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('corners', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Survey.Plot')),
            ],
        ),
        migrations.CreateModel(
            name='Cartographer',
            fields=[
                ('identifier', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('info_map', contractor.fields.MapField(blank=True, default=contractor.fields.defaultdict, editable=True, null=True)),
                ('last_checkin', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foundation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Building.Foundation')),
            ],
            options={
                'default_permissions': ('delete', 'view'),
                'permissions': (('can_assign_foundation', 'Can Assign Foundation to Cartographer'),)
            },
        ),
    ]
