#!/usr/bin/env python3
import os

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'contractor.settings' )

import django
django.setup()

import sys
import argparse
import subprocess
import getpass

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from contractor import settings
from contractor.lib.ip import CIDRSubnet, StrToIp, IpToStr
from contractor.BluePrint.models import FoundationBluePrint, StructureBluePrint
from contractor.Building.models import Structure
from contractor.Site.models import Site
from contractor.Survey.models import Plot
from contractor.Directory.models import Zone, Entry
from contractor.Utilities.models import Network, RealNetworkInterface, AddressBlock, Address, ReservedAddress, DynamicAddress, NetworkAddressBlock
from contractor.plugins.Manual.models import ManualFoundation

parser = argparse.ArgumentParser( description='Contractor SetupWizzard, must be run as root' )
parser.add_argument( '--root-password', help='password to use for the root user, if not specified it will be prompted for' )
parser.add_argument( '--no-ip-reservation', help='do not reserve static and dynamic ips', action='store_true' )
parser.add_argument( '--site-name', help='name of the initial site to create, default: site1', metavar='SITE', default='site1' )
parser.add_argument( '--site-domain', help='domain name of the initial site to create, default: site1.test', metavar='DOMAIN', default='site1.test' )
parser.add_argument( '--dns-server', help='set the dns server setting for the initial site, otherwise it will be set to the detected ip', metavar='IP ADDRESS' )
parser.add_argument( '--ntp-server', help='set the ntp server setting for the initial site, default: ntp.ubuntu.com', metavar='HOST', default='ntp.ubuntu.com' )
parser.add_argument( '--proxy-server', help='set the http proxy (mirror_proxy) setting for the initial site', metavar='HOST' )
parser.add_argument( '--primary-interface', help='which interface to use as the primary interface for the contractor structure, if not specified it will be auto detected', metavar='INTERFACE' )

args = parser.parse_args()

if os.getuid() != 0:
  print( 'This must be run as root' )
  sys.exit( 1 )

if args.root_password:
  root_password = args.root_password
else:
  print( 'Please Specify the password to use for the root user' )
  root_password = getpass.getpass()

print( 'Getting network config...' )

if args.primary_interface:
  contractor_iface = args.primary_interface
  contractor_gateway = None  # TODO: if this value get's used, need to do some /sbin/ip magic to find the gateway for this interface if there is one

else:
  line = subprocess.check_output( [ '/sbin/ip', 'route', 'get', '1.0.0.0' ], universal_newlines=True ).splitlines()[0]
  parts = line.split()
  contractor_iface = parts[4]
  contractor_gateway = parts[2]

print( 'Interface Name: "{0}"'.format( contractor_iface ) )

contractor_ip_address = None

for line in subprocess.check_output( [ '/sbin/ip', 'address', 'show', contractor_iface ], universal_newlines=True ).splitlines():
  parts = line.split()
  if parts[0] == 'inet':
    ( contractor_ip_address, network_prefix ) = parts[1].split( '/' )
    network_prefix = int( network_prefix )
    break

if contractor_ip_address is None:
  print( 'Unable to discover IP Address' )
  sys.exit( 1 )

contractor_dns = None
for line in open( '/etc/resolv.conf', 'r' ).readlines():
  parts = line.split()
  try:
    if parts[0] == 'nameserver':
      contractor_dns = parts[1]
      break

  except IndexError:
    continue

if contractor_dns is None:
  print( 'Unable to discover DNS' )
  sys.exit( 1 )

try:
  if args.primary_interface:
    contractor_iface, contractor_vlan = args.primary_interface.split( '.' )
  else:
    contractor_iface, contractor_vlan = contractor_iface.split( '.' )

except ValueError:
  contractor_vlan = 0

network_subnet = IpToStr( CIDRSubnet( StrToIp( contractor_ip_address ), network_prefix ) )

contractor_ip_offset = StrToIp( contractor_ip_address ) - StrToIp( network_subnet )

print( '  --- Detected Network Configuration ---')
print( '     Interface: "{0}"'.format( contractor_iface ) )
print( 'Network/Prefix: "{0}/{1}"'.format( network_subnet, network_prefix ) )
print( ' Contractor Ip: "{0}", offset "{1}"'.format( contractor_ip_address, contractor_ip_offset ) )
if contractor_gateway is not None:
  print( '       Gateway: "{0}"'.format( contractor_gateway ) )
print( '           DNS: "{0}"'.format( contractor_dns ) )
if contractor_vlan:
  print( '          VLAN: "{0}"'.format( contractor_vlan ) )
print()

if args.dns_server is None:
  args.dns_server = contractor_ip_address

search_list = []
tmp = args.site_domain.split( '.' )[ -1 ]
search_list.append( tmp )
for item in args.site_domain.split( '.' )[ -2::-1 ]:
  tmp = item + '.' + tmp
  search_list.append( tmp )
search_list.reverse()

print( '  === Values To Be Applied ===' )
print( 'Site name:        {0}'.format( args.site_name ) )
print( 'Domain:           {0}'.format( args.site_domain ) )
print( 'DNS Search Path:  {0}'.format( search_list ) )
print( 'DNS Server        {0}'.format( args.dns_server ) )
print( 'NTP Server        {0}'.format( args.ntp_server ) )
if args.proxy_server is not None:
  print( 'Proxy Server      {0}'.format( args.proxy_server  ) )

fbp_manual = FoundationBluePrint.objects.get( pk='manual-foundation-base' )
sbp_xenial = StructureBluePrint.objects.get( pk='manual-structure-base' )

print()
print( 'Creating test plot...' )
p1 = Plot( name='test', corners='Your testing area' )
p1.full_clean()
p1.save()

print( 'Creating site "{0}" ({1})...'.format( args.site_name, args.site_domain ) )
parent = None
for item in args.site_domain.split( '.' )[::-1]:
  zone = Zone()
  zone.name = item
  if parent is not None:
    zone.parent = parent
  zone.full_clean()
  zone.save()

  parent = zone

s1 = Site( name=args.site_name, description='Initial Site "{0}"'.format( args.site_name ) )
s1.zone = zone
s1.config_values[ 'domain_name' ] = args.site_domain
s1.config_values[ 'dns_search' ] = search_list
s1.config_values[ 'dns_servers' ] = [ args.dns_server ]
s1.config_values[ 'ntp_servers' ] = [ args.ntp_server ]

if args.proxy_server is not None:
  s1.config_values[ 'mirror_proxy' ] = args.proxy_server

s1.full_clean()
s1.save()

print( 'creating network...' )
ntwk = Network( name='main', site=s1 )
ntwk.full_clean()
ntwk.save()

if contractor_gateway is not None:
  gateway_offset = StrToIp( contractor_gateway ) - StrToIp( network_subnet )
  if gateway_offset < 1 or gateway_offset > 254:
    print( 'Bad caculated gateway offset: "{0}"'.format( gateway_offset ) )
  addr_block = AddressBlock( site=s1, subnet=network_subnet, gateway_offset=gateway_offset, prefix=network_prefix, name='main' )
else:
  addr_block = AddressBlock( site=s1, subnet=network_subnet, prefix=network_prefix, name='main' )

addr_block.full_clean()
addr_block.save()

nab = NetworkAddressBlock( network=ntwk, address_block=addr_block, vlan=contractor_vlan )
nab.full_clean()
nab.save()

print( 'creating contractor host...' )
fdn = ManualFoundation( site=s1, blueprint=fbp_manual, locator='contractor' )
fdn.full_clean()
fdn.save()
fdn.setBuilt()

iface = RealNetworkInterface( name=contractor_iface, is_provisioning=True, network=ntwk )
iface.foundation = fdn
iface.physical_location = contractor_iface
iface.full_clean()
iface.save()

strct = Structure( site=s1, blueprint=sbp_xenial, hostname='contractor', foundation=fdn )
strct.full_clean()
strct.save()
strct.setBuilt()

addr = Address( networked=strct, address_block=addr_block, interface_name=contractor_iface, offset=contractor_ip_offset, is_primary=True )
addr.full_clean()
addr.save()

e = Entry( type='CNAME' )
e.name = 'static'
e.target = 'contractor.{0}.'.format( args.site_domain )
e.full_clean()
e.save()

if not args.no_ip_reservation:
  print( 'reserving address offsets from 2 - 20...')
  for i in range( 2, 21 ):
    addr = ReservedAddress( address_block=addr_block, offset=i, reason='network reserved' )
    try:
      addr.full_clean()
    except ValidationError:
      print( 'WARNING offset "{0}" is allready in use, skipped.'.format( i ) )
      continue

    addr.save()

  print( 'using offsets 21 - 29 for dynamic pool...' )
  for i in range( 21, 30 ):
    addr = DynamicAddress( address_block=addr_block, offset=i )
    try:
      addr.full_clean()
    except ValidationError:
      print( 'WARNING offset "{0}" is allready in use, skipped.'.format( i ) )
      continue
    addr.save()

print( 'Configuring settings file...' )
filename = settings.__file__

configured = False
for line in open( filename, 'r' ).readlines():
  if line.startswith( 'BIND_NS_LIST =' ):
    parts = line.split( '=' )
    if parts[1].strip() != '[]':
      configured = True

    break

if not configured:
  data = open( filename, 'r' ).read()

  data = data.replace( 'BIND_NS_LIST = []', 'BIND_NS_LIST = {0}'.format( [ '{0}.contractor.{1}'.format( contractor_iface, args.site_domain ) ] ) )

  open( filename, 'w' ).write( data )

print( 'Generating Bind files...' )
subprocess.check_call( [ '/usr/lib/contractor/cron/genDNS' ] )

print( 'Configuring Bind...' )
configured = False
for line in open( '/etc/bind/named.conf.local', 'r' ).readlines():
  if line.strip() == 'include "/etc/bind/contractor/dns.master";':
    configured = True
    break

if not configured:
  fp = open( '/etc/bind/named.conf.local', 'w' )
  fp.write( """//
// Do any local configuration here
//

include "/etc/bind/contractor/dns.master";
""" )
  fp.close()

  fp = open( '/etc/bind/named.conf.options', 'w' )
  fp.write( """options {{
  directory "/var/cache/bind";

  forwarders {{
    {0};
  }};

  dnssec-validation no;

  auth-nxdomain no;    # conform to RFC1035
  listen-on-v6 {{ any; }};
}};
""".format( contractor_dns ) )
  fp.close()

print( 'Creating root user...' )
User.objects.create_superuser( username='root', password=root_password, email='root@{0}'.format( args.site_domain ) )

print( 'Done!' )
