#!/usr/bin/env python3
import os

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'contractor.settings' )

import django
django.setup()

from contractor.BluePrint.models import FoundationBluePrint, StructureBluePrint, Script
from contractor.Site.models import Site
from contractor.Building.models import Structure, FoundationNetworkInterface, ComplexStructure, Dependancy
from contractor.Utilities.models import RealNetworkInterface, AddressBlock, Address, ReservedAddress, DynamicAddress
from contractor_plugins.Manual.models import ManualFoundation, ManualComplex, ManualComplexedFoundation

fbp_manual = FoundationBluePrint.objects.get( pk='generic-manual' )
sbp_manual = StructureBluePrint.objects.get( pk='generic-manual-structure' )

print( 'creating sites...' )
s1 = Site( name='site1', description='Test Site 1' )
s1.config_values[ 'domain_name' ] = 'site1.local'
s1.config_values[ 'dns_servers' ] = [ '127.0.0.1' ]
s1.config_values[ 'dns_search' ] = [ 'site1.local', 'local' ]
s1.full_clean()
s1.save()

s2 = Site( name='site2', description='Test Site 2' )
s2.config_values[ 'domain_name' ] = 's2.site1.local'
s2.config_values[ '{dns_search' ] = [ 's2.site1.local' ]
s2.config_values[ 'dns_servers' ] = [ '10.0.0.1' ]
s2.parent = s1
s2.full_clean()
s2.save()

print( 'creating networks...' )
addr1_block = AddressBlock( site=s1, subnet='192.168.200.0', gateway_offset=1, prefix=24 )
addr1_block.full_clean()
addr1_block.save()

addr2_block = AddressBlock( site=s2, subnet='169.254.0.0', gateway_offset=1, prefix=24 )
addr2_block.full_clean()
addr2_block.save()

for i in range( 3, 10 ):
  addr = ReservedAddress( address_block=addr1_block, offset=i, reason='switch reserved' )
  addr.full_clean()
  addr.save()

addr = ReservedAddress( address_block=addr1_block, offset=10, reason='resource server' )
addr.full_clean()
addr.save()

for i in range( 220, 225 ):
  addr = DynamicAddress( address_block=addr1_block, offset=i )
  addr.full_clean()
  addr.save()

print( 'Creating Switch...' )
fdn_switch = ManualFoundation( site=s1, blueprint=fbp_manual, locator='switch' )
fdn_switch.full_clean()
fdn_switch.save()

iface = RealNetworkInterface( name='mgnt', is_provisioning=True )
iface.full_clean()
iface.save()

fni = FoundationNetworkInterface( foundation=fdn_switch, interface=iface, physical_location='mgnt' )
fni.full_clean()
fni.save()

for i in range( 0, 25 ):
  iface = RealNetworkInterface( name='fe0-{0}'.format( i ) )
  iface.full_clean()
  iface.save()

  fni = FoundationNetworkInterface( foundation=fdn_switch, interface=iface, physical_location='fe0-{0}'.format( i ) )
  fni.full_clean()
  fni.save()

str_switch = Structure( site=s1, blueprint=sbp_manual, hostname='switch', foundation=fdn_switch )
str_switch.full_clean()
str_switch.save()

addr = Address( networked=str_switch, address_block=addr1_block, interface_name='mgnt', offset=2, is_primary=True )
addr.full_clean()
addr.save()

print( 'Making a complex...' )
cpx = ManualComplex( site=s1, name='mnlcpx', description='manual complex', built_percentage=70 )
cpx.full_clean()
cpx.save()

for i in range( 1, 11 ):
  fdn = ManualFoundation( site=s1, blueprint=fbp_manual, locator='cpx{0}'.format( i ) )
  fdn.full_clean()
  fdn.save()

  iface = RealNetworkInterface( name='eth0', is_provisioning=True )
  iface.full_clean()
  iface.save()

  fni = FoundationNetworkInterface( foundation=fdn, interface=iface, physical_location='eth0' )
  fni.full_clean()
  fni.save()

  dep = Dependancy( foundation=fdn, structure=str_switch, link='soft' )
  dep.full_clean()
  dep.save()

  strct = Structure( site=s1, blueprint=sbp_manual, hostname='cpx{0}'.format( i ), foundation=fdn )
  strct.auto_build = True
  strct.full_clean()
  strct.save()

  addr = Address( networked=strct, address_block=addr1_block, interface_name='eth0', offset=20 + i, is_primary=True )
  addr.full_clean()
  addr.save()

  cpx_member = ComplexStructure( complex=cpx, structure=strct )
  cpx_member.full_clean()
  cpx_member.save()

fdn_strmgr = ManualFoundation( site=s1, blueprint=fbp_manual, locator='strgmgr')
fdn_strmgr.full_clean()
fdn_strmgr.save()

iface = RealNetworkInterface( name='eth0', is_provisioning=True )
iface.full_clean()
iface.save()

fni = FoundationNetworkInterface( foundation=fdn_strmgr, interface=iface, physical_location='eth0' )
fni.full_clean()
fni.save()

dep = Dependancy( foundation=fdn_strmgr, structure=str_switch, link='soft' )
dep.full_clean()
dep.save()

strct_strmgr = Structure( site=s1, blueprint=sbp_manual, hostname='strgmgr', foundation=fdn_strmgr )
strct_strmgr.auto_build = True
strct_strmgr.full_clean()
strct_strmgr.save()

addr = Address( networked=strct_strmgr, address_block=addr1_block, interface_name='eth0', offset=40, is_primary=True )
addr.full_clean()
addr.save()

print( 'Making a storage cluster...' )
for i in range( 1, 5 ):
  fdn = ManualFoundation( site=s1, blueprint=fbp_manual, locator='strg{0}'.format( i ) )
  fdn.full_clean()
  fdn.save()

  iface = RealNetworkInterface( name='eth0', is_provisioning=True )
  iface.full_clean()
  iface.save()

  fni = FoundationNetworkInterface( foundation=fdn, interface=iface, physical_location='eth0' )
  fni.full_clean()
  fni.save()

  dep = Dependancy( foundation=fdn, structure=str_switch, link='soft' )
  dep.full_clean()
  dep.save()

  strct = Structure( site=s1, blueprint=sbp_manual, hostname='strg{0}'.format( i ), foundation=fdn )
  strct.auto_build = True
  strct.full_clean()
  strct.save()

  addr = Address( networked=strct, address_block=addr1_block, interface_name='eth0', offset=40 + i, is_primary=True )
  addr.full_clean()
  addr.save()

  dep = Dependancy( foundation=fdn_strmgr, structure=strct, link='soft' )
  dep.full_clean()
  dep.save()

print( 'Adding to Complex...' )
for i in range( 1, 5 ):
  fdn = ManualComplexedFoundation( site=s1, blueprint=fbp_manual, locator='cpxmbr{0}'.format( i ), complex_host=cpx )
  fdn.full_clean()
  fdn.save()

  iface = RealNetworkInterface( name='eth0', is_provisioning=True )
  iface.full_clean()
  iface.save()

  fni = FoundationNetworkInterface( foundation=fdn, interface=iface, physical_location='eth0' )
  fni.full_clean()
  fni.save()

  dep = Dependancy( foundation=fdn, structure=strct_strmgr, script_name='utility', link='soft' )
  dep.full_clean()
  dep.save()

  strct = Structure( site=s1, blueprint=sbp_manual, hostname='cpxmbr{0}'.format( i ), foundation=fdn )
  strct.auto_build = True
  strct.full_clean()
  strct.save()

  addr = Address( networked=strct, address_block=addr1_block, interface_name='eth0', offset=100 + i, is_primary=True )
  addr.full_clean()
  addr.save()


if True:  # change to True for demo mode
  for name in ( 'create-generic-manual', 'destroy-generic-manual', 'utility-generic-manual', 'create-manual-structure', 'destroy-manual-structure', 'utility-manual-structure' ):
    print( name )
    script = Script.objects.get( name=name )
    script.script = 'delay( seconds=5 )'
    script.full_clean()
    script.save()
