#!/usr/bin/env python3
import os
import sys
import argparse

sys.path.insert( 1, '../..' )

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'contractor.settings' )
import django
django.setup()

from contractor.BluePrint.models import FoundationBluePrint, StructureBluePrint
from contractor.Site.models import Site
from contractor.Building.models import Foundation, Structure

fbp_vm = FoundationBluePrint.objects.get( pk='generic-virtualbox' )
sbp_xenial = StructureBluePrint.objects.get( pk='generic-xenial' )

print( 'creating sites...' )
s1 = Site( name='site1', description='Test Site 1' )
s1.config_values[ 'domain_name' ] = 'site1.local'
s1.config_values[ 'dns_servers' ] = [ '127.0.0.1' ]
s1.config_values[ 'dns_search' ] = [ 'site1.local', 'local' ]
s1.full_clean()
s1.save()

s2 = Site( name='site2', description='Test Site 2' )
s2.config_values[ 'domain_name' ] = 's2.site1.local'
s2.config_values[ '{dns_search' ] = [ 's2.site1.local' ]
s2.config_values[ 'dns_servers' ] = [ '10.0.0.1' ]
s2.parent = s1
s2.full_clean()
s2.save()

print( 'creating foundations...' )
fdn_vm1 = Foundation( site=s1, blueprint=fbp_vm, locator='testvm1' )
fdn_vm1.full_clean()
fdn_vm1.save()

print( 'creating structures...' )
str_vm1 = Structure( site=s1, blueprint=sbp_xenial, hostname='testvm1' )
str_vm1.foundation = fdn_vm1
str_vm1.full_clean()
str_vm1.save()
